export const GET_STORIES_REQUESTED = "GET_STORIES_REQUESTED";
export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";
export const GET_STORIES_FAILED = "GET_STORIES_FAILED";
export const GET_ARTICLES_REQUESTED = 'GET_ARTICLES_REQUESTED';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';
